// EN, JP, DE, ES, KO, ZH translation variables for Monos

const LANG_EN = {
    GREETING: "Monos loaded successfully",
    LICENCE: "Monos is made by Monos Corporation, and is licensed under the CC BY-NC 4.0",
    WELCOME_MESSAGE: "Hello, welcome to Monos!",
    PLACEHOLDER_MESSAGE: "Type your message",
    SEND: "Send",
    VOICE: "Voice",
    CONTROLS: "Controls",
    SILENT: "Mute",
    TONE: "Screen temperature",
    MINIMAL: "Minimal mode",
    DARKMODE: "Dark mode",
    WEATHER: "Weather",
    GURAPPS: "Gurapps",
    SECONDS: "Seconds",
    MOTION: "Motion",
    CONTRAST: "Contrast",
    WALLPAPER: "Wallpaper",
    ADD: "Add",
    STYLE: "Style",
    WEIGHT: "Weight",
    ALIGNMENT: "Alignment",
    ALIGN_CENTER: "Center",
    ALIGN_LEFT: "Left",
    ALIGN_RIGHT: "Right",
    ADJUST: "Adjust",
    LANGPICK: "Language",
    RESET: "Wipe data",
    RESET_BTN: "Reset",
    INSTALL_PROMPT: "Install as an app to get all features",
    OFFLINE: "You are offline",
    ONLINE: "You are online",
    FAIL_WEATHER: "Failed to retrieve weather",
    FULLSCREEN: "Fullscreen",
    SETUP_COMPLETE: "Setup complete",
    OPEN_SETTINGS: "Opening Settings",
    OPEN_WEATHER: "Opening Weather",
    APP_OPENED: "{app} app opened",
    APP_OPEN_FAIL: "Failed to open {app}",
    WALLPAPER_UPDATED: "Wallpaper updated",
    WALLPAPER_UPDATE_FAIL: "Failed to update wallpaper",
    MULTIPLE_WALLPAPERS_UPDATED: "Multiple wallpapers updated",
    NO_VALID_WALLPAPERS: "No valid wallpapers found",
    WALLPAPER_CHANGE: "Wallpaper changed",
    SLIDESHOW_WALLPAPER: "Slideshow wallpaper",
    WALLPAPER_SAVE_FAIL: "Failed to save wallpaper",
    WALLPAPER_HISTORY_FAIL: "Failed to save wallpaper history",
    ALL_WALLPAPER_REMOVE: "All wallpapers removed",
    WALLPAPER_REMOVE: "Wallpaper removed",
    LOAD_SUCCESS: "Monos loaded successfully",
    NOT_FULLSCREEN: "Not fullscreen",
    CLOCK_STYLE_FAILED: "Failed to load Clock Style",
    CHECK_WORDS: ['updated', 'complete', 'done', 'success', 'completed', 'ready', 'successfully', 'accepted', 'accept', 'yes'],
    CLOSE_WORDS: ['failed', 'canceled', 'error', 'failure', 'fail', 'cancel', 'rejected', 'reject', 'not', 'no'],
    DEFAULT: "Default",
    WORK: "Work",
    PUFFY: "Puffy",
    CLASSIC: "Classic",
    STROKES: "Strokes",
    MONO: "Mono",
    PIXEL: "Pixel",
    WRITTEN: "Written",
    RAISED: "Raised",
    DOT: "Dot",
    ROUND: "Round",
    DETAIL_VERS: "Details",
    GET_DOCS: "Open Docs",
    SETUP_SELECT_LANGUAGE: "Select Language",
    SETUP_SELECT_LANGUAGE_DESC: "You can change languages later in Controls ",
    SETUP_HI_THERE: "Hi there",
    SETUP_OPEN_PRIVATE: "Open & Private",
    SETUP_OPEN_PRIVATE_DESC: "Your data stays on device at all times. No user data is transferred to any of our services.",
    SETUP_ALLOW_PERMISSIONS: "Allow Permissions",
    SETUP_BASIC_ACCESS: "Basic access",
    SETUP_BASIC_ACCESS_DESC: "Enables Monos to work properly",
    SETUP_LOCATION_ACCESS: "Location Access",
    SETUP_LOCATION_ACCESS_DESC: "Enables Weather and personalized results",
    SETUP_NOTIFICATIONS: "Notifications",
    SETUP_NOTIFICATIONS_DESC: "Enables updates and timer alerts",
    SETUP_CANNIBALIZE: "Personalize your Monos",
    SETUP_CLOCK_FORMAT: "Clock Format",
    SETUP_SHOW_SECONDS: "Show Seconds",
    SETUP_HIDE_SECONDS: "Hide Seconds",
    SETUP_SHOW_WEATHER: "Show or Hide Weather",
    SETUP_SHOW_WEATHER_TRUE: "Show Weather",
    SETUP_SHOW_WEATHER_FALSE: "Hide Weather",
    SETUP_GURAPPS_USAGE: "Gurapps Usage",
    SETUP_GURAPPS_USAGE_DESC: "To use Gurapps, swipe up from the bottom pill and choose an Gurapp to launch.",
    SETUP_CONFIGURE_OPTIONS: "Configure more Options in Controls",
    SETUP_CONFIGURE_OPTIONS_DESC: "Press on Controls on the top right or access Controls in app by pressing on the clock.",
    SETUP_GET_STARTED: "Get Started",
    SETUP_CONTINUE: "Continue",
    SETUP_LIGHT: "Light",
    SETUP_DARK: "Dark",
    RESET_OPTIONS: "Select OK for a full reset or Cancel for clock settings reset only",
    CLOCK_RESET_SUCCESS: "Clock data has been successfully cleared.",
    RESET_CONFIRM: "Are you sure you want to clear all data? This action cannot be undone.",
    RESET_SUCCESS: "All data has been successfully cleared.",
    LARGE_SCR_REQ: "Larger screen is required",
    DONT_CLOSE: "Use Sleep in Controls to turn off",
    CLOCK_COLOR: "Clock Color",
    N_WALL: "No wallpapers",
    CLOCK_STACK: "Clock Stack",
    GURAPP_OFF: "Gurapps are currently disabled",
    GURAPP_NOT_INSTALLED: "This app is not installed",
    GURAPP_OFFLINE_NOT_SUPPORTED: "Offline installation not supported by this browser",
    GURAPP_INSTALL_FAILED: "Offline installation failed for {appName}",
    GURAPP_DELETED: "{appName} was deleted",
    GURAPP_DELETE_FAILED: "Error: Could not find {appName} to delete",
    GURAPP_DELETE_ASK: "Are you sure you want to delete {appName}?",
    GURAPP_DELETE_STORE_DENIED: "The App Store cannot be deleted",
    GURAPP_INSTALLING: "Installing {appName}",
    GURAPP_INSTALL_EXISTS: "{appName} is already installed",
    GURAPP_INSTALL_NONSTORE_DENIED: "Error: only the Monos App Store can install apps"
};

const LANG_JP = {
    GREETING: "Monos を正常に読み込みました。",
    LICENCE: "Monos は kirbIndustries によって作成され、CC BY-NC 4.0 の下でライセンスされています。",
    WELCOME_MESSAGE: "こんにちは、Monosへようこそ！",
    PLACEHOLDER_MESSAGE: "メッセージを入力してください",
    SEND: "送信",
    VOICE: "音声",
    CONTROLS: "コントロール",
    SILENT: "サイレント",
    TONE: "トーン",
    MINIMAL: "集中",
    DARKMODE: "昼光",
    WEATHER: "天気",
    GURAPPS: "グーラのアプリ",
    SECONDS: "セコンド",
    MOTION: "モーション",
    CONTRAST: "コントラスト",
    WALLPAPER: "壁紙",
    ADD: "追加",
    STYLE: "スタイル",
    WEIGHT: "太さ",
    ALIGNMENT: "配置",
    ALIGN_CENTER: "中央",
    ALIGN_LEFT: "左",
    ALIGN_RIGHT: "右",
    ADJUST: "調整",
    LANGPICK: "言語",
    RESET: "データを消去",
    RESET_BTN: "リセット",
    INSTALL_PROMPT: "アプリとしてインストールしてすべての機能を利用",
    OFFLINE: "オフラインです",
    ONLINE: "オンラインです",
    FAIL_WEATHER: "天気を取得できませんでした",
    FULLSCREEN: "全画面",
    SETUP_COMPLETE: "セットアップ完了",
    OPEN_SETTINGS: "設定を開いています",
    OPEN_WEATHER: "天気を開いています",
    APP_OPENED: "{app} アプリを開きました",
    APP_OPEN_FAIL: "{app} を開けませんでした",
    WALLPAPER_UPDATED: "壁紙が更新されました",
    WALLPAPER_UPDATE_FAIL: "壁紙の更新に失敗しました",
    MULTIPLE_WALLPAPERS_UPDATED: "複数の壁紙が更新されました",
    NO_VALID_WALLPAPERS: "有効な壁紙が見つかりませんでした",
    WALLPAPER_CHANGE: "壁紙が変更されました",
    SLIDESHOW_WALLPAPER: "スライドショーの壁紙",
    WALLPAPER_SAVE_FAIL: "壁紙の保存に失敗しました",
    WALLPAPER_HISTORY_FAIL: "壁紙履歴の保存に失敗しました",
    ALL_WALLPAPER_REMOVE: "すべての壁紙を削除しました",
    WALLPAPER_REMOVE: "壁紙を削除しました",
    LOAD_SUCCESS: "ぐらするらいす読み込み成功",
    NOT_FULLSCREEN: "全画面ではありません",
    CLOCK_STYLE_FAILED: "クロックスタイルのロードに失敗しました",
    CHECK_WORDS: ['更新', '完了', '成功', '準備完了', '受け入れ', 'はい'],
    CLOSE_WORDS: ['失敗', 'キャンセル', 'エラー', '故障', '拒否', '違う', 'いいえ'],
    DEFAULT: "デフォルト",
    WORK: "仕事",
    PUFFY: "ふっくら",
    CLASSIC: "クラシック",
    STROKES: "ストローク",
    MONO: "モノ",
    PIXEL: "ピクセル",
    WRITTEN: "手書き",
    RAISED: "隆起",
    DOT: "ドット",
    ROUND: "丸い",
    DETAIL_VERS: "詳細",
    GET_DOCS: "ドキュメントを開く",
    SETUP_SELECT_LANGUAGE: "言語を選択",
    SETUP_SELECT_LANGUAGE_DESC: "コントロールで後で言語を変更できます ",
    SETUP_HI_THERE: "こんにちは",
    SETUP_OPEN_PRIVATE: "オープン＆プライベート",
    SETUP_OPEN_PRIVATE_DESC: "あなたのデータは常にデバイス上に保持されます。ユーザーデータは当社のサービスに転送されません。",
    SETUP_ALLOW_PERMISSIONS: "許可を与える",
    SETUP_BASIC_ACCESS: "基本アクセス",
    SETUP_BASIC_ACCESS_DESC: "Monosが適切に動作するようにします",
    SETUP_LOCATION_ACCESS: "位置情報アクセス",
    SETUP_LOCATION_ACCESS_DESC: "天気とパーソナライズされた結果を有効にします",
    SETUP_NOTIFICATIONS: "通知",
    SETUP_NOTIFICATIONS_DESC: "更新とタイマーアラートを有効にします",
    SETUP_CANNIBALIZE: "Monosをカスタマイズ",
    SETUP_CLOCK_FORMAT: "時計の形式",
    SETUP_SHOW_SECONDS: "秒を表示",
    SETUP_HIDE_SECONDS: "秒を非表示",
    SETUP_SHOW_WEATHER: "天気表示の切り替え",
    SETUP_SHOW_WEATHER_TRUE: "天気表示",
    SETUP_SHOW_WEATHER_FALSE: "天気非表示",
    SETUP_GURAPPS_USAGE: "グーラのアプリの使用",
    SETUP_GURAPPS_USAGE_DESC: "グーラのアプリを使用するには、下のピルから上にスワイプしてGurappを選択して起動します。",
    SETUP_CONFIGURE_OPTIONS: "コントロールで詳細設定",
    SETUP_CONFIGURE_OPTIONS_DESC: "右上のコントロールを押すか、時計を押してアプリ内のコントロールにアクセスします。",
    SETUP_GET_STARTED: "開始",
    SETUP_CONTINUE: "続ける",
    SETUP_LIGHT: "ライト",
    SETUP_DARK: "ダーク",
    RESET_OPTIONS: "完全なリセットにはOKを選択し、時計の設定のみのリセットにはキャンセルを選択してください",
    CLOCK_RESET_SUCCESS: "時計データが正常にクリアされました。",
    RESET_CONFIRM: "すべてのデータを消去してもよろしいですか？この操作は元に戻せません。",
    RESET_SUCCESS: "すべてのデータが正常に消去されました。",
    LARGE_SCR_REQ: "より大きな画面が必要です",
    DONT_CLOSE: "オフにするにはコントロールでスリープを使用してください",
    CLOCK_COLOR: "時計の色",
    N_WALL: "壁紙がありません",
    CLOCK_STACK: "クロックスタック",
    GURAPP_OFF: "Gurapps は現在無効です",
    GURAPP_NOT_INSTALLED: "このアプリはインストールされていません",
    GURAPP_OFFLINE_NOT_SUPPORTED: "このブラウザではオフラインインストールはサポートされていません",
    GURAPP_INSTALL_FAILED: "{appName} のオフラインインストールに失敗しました",
    GURAPP_DELETED: "{appName} は削除されました",
    GURAPP_DELETE_FAILED: "エラー: 削除する {appName} が見つかりませんでした",
    GURAPP_DELETE_ASK: "{appName} を削除してもよろしいですか？",
    GURAPP_DELETE_STORE_DENIED: "App Store は削除できません",
    GURAPP_INSTALLING: "{appName} をインストール中",
    GURAPP_INSTALL_EXISTS: "{appName} はすでにインストールされています",
    GURAPP_INSTALL_NONSTORE_DENIED: "エラー: Monos App Store のみがアプリをインストールできます"
};

const LANG_DE = {
    GREETING: "Monos erfolgreich geladen",
    LICENCE: "Monos wird von kirbIndustries erstellt und ist unter der CC BY-NC 4.0 lizenziert.",
    WELCOME_MESSAGE: "Hallo, willkommen bei Monos!",
    PLACEHOLDER_MESSAGE: "Geben Sie Ihre Nachricht ein",
    SEND: "Senden",
    VOICE: "Sprache",
    CONTROLS: "Steuerelemente",
    SILENT: "Stumm",
    TONE: "Ton",
    MINIMAL: "Fokus",
    DARKMODE: "Tageslicht",
    WEATHER: "Wetter",
    GURAPPS: "Gura-Anwendungen",
    SECONDS: "Sekunden",
    MOTION: "Bewegung",
    CONTRAST: "Kontrast",
    WALLPAPER: "Hintergrundbild",
    ADD: "Hinzufügen",
    STYLE: "Stil",
    WEIGHT: "Gewicht",
    ALIGNMENT: "Ausrichtung",
    ALIGN_CENTER: "Zentriert",
    ALIGN_LEFT: "Links",
    ALIGN_RIGHT: "Rechts",
    ADJUST: "Anpassen",
    LANGPICK: "Sprache",
    RESET: "Daten löschen",
    RESET_BTN: "Zurücksetzen",
    INSTALL_PROMPT: "Als App installieren, um alle Funktionen zu erhalten",
    OFFLINE: "Sie sind offline",
    ONLINE: "Sie sind online",
    FAIL_WEATHER: "Wetter konnte nicht abgerufen werden",
    FULLSCREEN: "Vollbild",
    SETUP_COMPLETE: "Einrichtung abgeschlossen",
    OPEN_SETTINGS: "Einstellungen öffnen",
    OPEN_WEATHER: "Wetter öffnen",
    APP_OPENED: "App {app} geöffnet",
    APP_OPEN_FAIL: "App {app} konnte nicht geöffnet werden",
    WALLPAPER_UPDATED: "Hintergrundbild aktualisiert",
    WALLPAPER_UPDATE_FAIL: "Hintergrundbild konnte nicht aktualisiert werden",
    MULTIPLE_WALLPAPERS_UPDATED: "Mehrere Hintergrundbilder aktualisiert",
    NO_VALID_WALLPAPERS: "Keine gültigen Hintergrundbilder gefunden",
    WALLPAPER_CHANGE: "Hintergrundbild geändert",
    SLIDESHOW_WALLPAPER: "Diashow-Hintergrundbild",
    WALLPAPER_SAVE_FAIL: "Hintergrundbild konnte nicht gespeichert werden",
    WALLPAPER_HISTORY_FAIL: "Hintergrundbildverlauf konnte nicht gespeichert werden",
    ALL_WALLPAPER_REMOVE: "Alle Hintergrundbilder entfernt",
    WALLPAPER_REMOVE: "Hintergrundbild entfernt",
    LOAD_SUCCESS: "Monos erfolgreich geladen",
    NOT_FULLSCREEN: "Nicht im Vollbildmodus",
    CLOCK_STYLE_FAILED: "Uhrstil konnte nicht geladen werden",
    CHECK_WORDS: ['aktualisiert', 'abgeschlossen', 'fertig', 'erfolg', 'erfolgreich', 'akzeptiert', 'akzeptieren', 'ja'],
    CLOSE_WORDS: ['fehlgeschlagen', 'abgebrochen', 'fehler', 'fehler', 'abbrechen', 'abgelehnt', 'ablehnen', 'nein'],
    DEFAULT: "Standard",
    WORK: "Arbeit",
    PUFFY: "Puffy",
    CLASSIC: "Klassisch",
    STROKES: "Striche",
    MONO: "Mono",
    PIXEL: "Pixel",
    WRITTEN: "Geschrieben",
    RAISED: "Erhoben",
    DOT: "Punkt",
    ROUND: "Rund",
    DETAIL_VERS: "Details",
    GET_DOCS: "Dokumente öffnen",
    SETUP_SELECT_LANGUAGE: "Sprache auswählen",
    SETUP_SELECT_LANGUAGE_DESC: "Sie können die Sprachen später in der Steuerung ändern ",
    SETUP_HI_THERE: "Hallo",
    SETUP_OPEN_PRIVATE: "Offen & Privat",
    SETUP_OPEN_PRIVATE_DESC: "Ihre Daten bleiben jederzeit auf dem Gerät. Es werden keine Benutzerdaten an unsere Dienste übertragen.",
    SETUP_ALLOW_PERMISSIONS: "Berechtigungen zulassen",
    SETUP_BASIC_ACCESS: "Grundlegender Zugriff",
    SETUP_BASIC_ACCESS_DESC: "Ermöglicht das ordnungsgemäße Funktionieren von Monos",
    SETUP_LOCATION_ACCESS: "Standortzugriff",
    SETUP_LOCATION_ACCESS_DESC: "Ermöglicht Wetter und personalisierte Ergebnisse",
    SETUP_NOTIFICATIONS: "Benachrichtigungen",
    SETUP_NOTIFICATIONS_DESC: "Ermöglicht Updates und Timer-Benachrichtigungen",
    SETUP_CANNIBALIZE: "Monos anpassen",
    SETUP_CLOCK_FORMAT: "Uhrenformat",
    SETUP_SHOW_SECONDS: "Sekunden anzeigen",
    SETUP_HIDE_SECONDS: "Sekunden ausblenden",
    SETUP_SHOW_WEATHER: "Wetter anzeigen oder ausblenden",
    SETUP_SHOW_WEATHER_TRUE: "Wetter anzeigen",
    SETUP_SHOW_WEATHER_FALSE: "Wetter ausblenden",
    SETUP_GURAPPS_USAGE: "Gura-Anwendungen-Nutzung",
    SETUP_GURAPPS_USAGE_DESC: "Um Gura-Anwendungen zu verwenden, wischen Sie vom unteren Balken nach oben und wählen Sie eine Gurapp zum Starten aus.",
    SETUP_CONFIGURE_OPTIONS: "Weitere Optionen in den Einstellungen konfigurieren",
    SETUP_CONFIGURE_OPTIONS_DESC: "Drücken Sie oben rechts auf Einstellungen oder greifen Sie auf Einstellungen in der App zu, indem Sie auf die Uhr drücken.",
    SETUP_GET_STARTED: "Starten",
    SETUP_CONTINUE: "Weiter",
    SETUP_LIGHT: "Hell",
    SETUP_DARK: "Dunkel",
    RESET_OPTIONS: "Wählen Sie OK für einen vollständigen Reset oder Abbrechen für das Zurücksetzen nur der Uhreinstellungen",
    CLOCK_RESET_SUCCESS: "Uhrdaten wurden erfolgreich gelöscht.",
    RESET_CONFIRM: "Möchten Sie wirklich alle Daten löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
    RESET_SUCCESS: "Alle Daten wurden erfolgreich gelöscht.",
    LARGE_SCR_REQ: "Größerer Bildschirm erforderlich",
    DONT_CLOSE: "Verwenden Sie den Schlafmodus in den Steuerelementen, um ihn auszuschalten",
    CLOCK_COLOR: "Uhrenfarbe",
    N_WALL: "Keine Hintergrundbilder",
    CLOCK_STACK: "Uhr-Stapel",
    GURAPP_OFF: "Gurapps sind derzeit deaktiviert",
    GURAPP_NOT_INSTALLED: "Diese App ist nicht installiert",
    GURAPP_OFFLINE_NOT_SUPPORTED: "Offline-Installation wird von diesem Browser nicht unterstützt",
    GURAPP_INSTALL_FAILED: "Offline-Installation für {appName} fehlgeschlagen",
    GURAPP_DELETED: "{appName} wurde gelöscht",
    GURAPP_DELETE_FAILED: "Fehler: {appName} zum Löschen nicht gefunden",
    GURAPP_DELETE_ASK: "Möchten Sie {appName} wirklich löschen?",
    GURAPP_DELETE_STORE_DENIED: "Der App Store kann nicht gelöscht werden",
    GURAPP_INSTALLING: "Installiere {appName}",
    GURAPP_INSTALL_EXISTS: "{appName} ist bereits installiert",
    GURAPP_INSTALL_NONSTORE_DENIED: "Fehler: Nur der Monos App Store kann Apps installieren"
};

const LANG_FR = {
    GREETING: "Monos chargé avec succès",
    LICENCE: "Monos est créé par kirbIndustries, et est sous licence CC BY-NC 4.0",
    WELCOME_MESSAGE: "Bonjour, bienvenue sur Monos!",
    PLACEHOLDER_MESSAGE: "Tapez votre message",
    SEND: "Envoyer",
    VOICE: "Voix",
    CONTROLS: "Contrôles",
    SILENT: "Silencieux",
    TONE: "Tonalité",
    MINIMAL: "Focus",
    DARKMODE: "Lumière",
    WEATHER: "Météo",
    GURAPPS: "Applications Gura",
    SECONDS: "Secondes",
    MOTION: "Mouvement",
    CONTRAST: "Contraste",
    WALLPAPER: "Fond d'écran",
    ADD: "Ajouter",
    STYLE: "Style",
    WEIGHT: "Poids",
    ALIGNMENT: "Alignement",
    ALIGN_CENTER: "Centré",
    ALIGN_LEFT: "Gauche",
    ALIGN_RIGHT: "Droite",
    ADJUST: "Ajuster",
    LANGPICK: "Langue",
    RESET: "Effacer les données",
    RESET_BTN: "Réinitialiser",
    INSTALL_PROMPT: "Installez en tant qu'application pour obtenir toutes les fonctionnalités",
    OFFLINE: "Vous êtes hors ligne",
    ONLINE: "Vous êtes en ligne",
    FAIL_WEATHER: "Impossible de récupérer la météo",
    FULLSCREEN: "Plein écran",
    SETUP_COMPLETE: "Configuration terminée",
    OPEN_SETTINGS: "Ouverture des paramètres",
    OPEN_WEATHER: "Ouverture de la météo",
    APP_OPENED: "L'application {app} est ouverte",
    APP_OPEN_FAIL: "Impossible d'ouvrir {app}",
    WALLPAPER_UPDATED: "Fond d'écran mis à jour",
    WALLPAPER_UPDATE_FAIL: "Impossible de mettre à jour le fond d'écran",
    MULTIPLE_WALLPAPERS_UPDATED: "Plusieurs fonds d'écran mis à jour",
    NO_VALID_WALLPAPERS: "Aucun fond d'écran valide trouvé",
    WALLPAPER_CHANGE: "Fond d'écran changé",
    SLIDESHOW_WALLPAPER: "Fond d'écran en diaporama",
    WALLPAPER_SAVE_FAIL: "Impossible de sauvegarder le fond d'écran",
    WALLPAPER_HISTORY_FAIL: "Impossible de sauvegarder l'historique des fonds d'écran",
    ALL_WALLPAPER_REMOVE: "Tous les fonds d'écran supprimés",
    WALLPAPER_REMOVE: "Fond d'écran supprimé",
    LOAD_SUCCESS: "Monoschargé avec succès",
    NOT_FULLSCREEN: "Pas en plein écran",
    CLOCK_STYLE_FAILED: "Impossible de charger le style d'horloge",
    CHECK_WORDS: ['mis à jour', 'terminé', 'fait', 'succès', 'complété', 'prêt', 'avec succès', 'accepté', 'accepter', 'oui'],
    CLOSE_WORDS: ['échoué', 'annulé', 'erreur', 'échec', 'rater', 'annuler', 'rejeté', 'rejeter', 'pas', 'non'],
    DEFAULT: "Par défaut",
    WORK: "Travail",
    PUFFY: "Gonflé",
    CLASSIC: "Classique",
    STROKES: "Traits",
    MONO: "Mono",
    PIXEL: "Pixel",
    WRITTEN: "Écrit",
    RAISED: "En relief",
    DOT: "Point",
    ROUND: "Rond",
    DETAIL_VERS: "Détails",
    GET_DOCS: "Ouvrir la docs",
    SETUP_SELECT_LANGUAGE: "Sélectionner la langue",
    SETUP_SELECT_LANGUAGE_DESC: "Vous pouvez changer de langue plus tard dans les contrôles ", 
    SETUP_HI_THERE: "Bonjour",
    SETUP_OPEN_PRIVATE: "Ouvert & Privé",
    SETUP_OPEN_PRIVATE_DESC: "Vos données restent sur l'appareil à tout moment. Aucune donnée utilisateur n'est transférée à nos services.",
    SETUP_ALLOW_PERMISSIONS: "Autoriser les permissions",
    SETUP_BASIC_ACCESS: "Accès de base",
    SETUP_BASIC_ACCESS_DESC: "Permet à Monosde fonctionner correctement",
    SETUP_LOCATION_ACCESS: "Accès à la localisation",
    SETUP_LOCATION_ACCESS_DESC: "Permet la météo et les résultats personnalisés",
    SETUP_NOTIFICATIONS: "Notifications",
    SETUP_NOTIFICATIONS_DESC: "Permet les mises à jour et les alertes de minuterie",
    SETUP_CANNIBALIZE: "Personnaliser votre Monos",
    SETUP_CLOCK_FORMAT: "Format de l'horloge",
    SETUP_SHOW_SECONDS: "Afficher les secondes",
    SETUP_HIDE_SECONDS: "Masquer les secondes",
    SETUP_SHOW_WEATHER: "Afficher ou masquer la météo",
    SETUP_SHOW_WEATHER_TRUE: "Afficher la météo",
    SETUP_SHOW_WEATHER_FALSE: "Masquer la météo",
    SETUP_GURAPPS_USAGE: "Utilisation de Applications Gura",
    SETUP_GURAPPS_USAGE_DESC: "Pour utiliser Applications Gura, glissez vers le haut depuis la barre du bas et choisissez une Gurapp à lancer.",
    SETUP_CONFIGURE_OPTIONS: "Configurer plus d'options dans les paramètres",
    SETUP_CONFIGURE_OPTIONS_DESC: "Appuyez sur Paramètres en haut à droite ou accédez aux Paramètres dans l'application en appuyant sur l'horloge.",
    SETUP_GET_STARTED: "Commencer",
    SETUP_CONTINUE: "Continuer",
    SETUP_LIGHT: "Clair",
    SETUP_DARK: "Sombre",
    RESET_OPTIONS: "Sélectionnez OK pour une réinitialisation complète ou Annuler pour réinitialiser uniquement les paramètres de l'horloge",
    CLOCK_RESET_SUCCESS: "Les données de l'horloge ont été effacées avec succès.",
    RESET_CONFIRM: "Êtes-vous sûr de vouloir effacer toutes les données ? Cette action est irréversible.",
    RESET_SUCCESS: "Toutes les données ont été effacées avec succès.",
    LARGE_SCR_REQ: "Un écran plus grand est nécessaire",
    DONT_CLOSE: "Utilisez le mode veille dans les commandes pour éteindre",
    CLOCK_COLOR: "Couleur de l'horloge",
    N_WALL: "Pas de fonds d'écran",
    CLOCK_STACK: "Pile d'horloge",
    GURAPP_OFF: "Les Gurapps sont actuellement désactivées",
    GURAPP_NOT_INSTALLED: "Cette application n'est pas installée",
    GURAPP_OFFLINE_NOT_SUPPORTED: "L'installation hors ligne n'est pas prise en charge par ce navigateur",
    GURAPP_INSTALL_FAILED: "L'installation hors ligne a échoué pour {appName}",
    GURAPP_DELETED: "{appName} a été supprimée",
    GURAPP_DELETE_FAILED: "Erreur : Impossible de trouver {appName} à supprimer",
    GURAPP_DELETE_ASK: "Êtes-vous sûr de vouloir supprimer {appName} ?",
    GURAPP_DELETE_STORE_DENIED: "L'App Store ne peut pas être supprimé",
    GURAPP_INSTALLING: "Installation de {appName}",
    GURAPP_INSTALL_EXISTS: "{appName} est déjà installé",
    GURAPP_INSTALL_NONSTORE_DENIED: "Erreur : Seul le MonosApp Store peut installer des applications"
};

const LANG_ES = {
    GREETING: "Monoscargado con éxito",
    LICENCE: "Monoses creado por kirbIndustries y está licenciado bajo la Licencia Pública General de GNU, Versión 2.0 (GPL-2.0).",
    WELCOME_MESSAGE: "¡Hola, bienvenido a Monos!",
    PLACEHOLDER_MESSAGE: "Escriba su mensaje",
    SEND: "Enviar",
    VOICE: "Voz",
    CONTROLS: "Controles",
    SILENT: "Silencio",
    TONE: "Tono",
    MINIMAL: "Enfoque",
    DARKMODE: "Luz del día",
    WEATHER: "Clima",
    GURAPPS: "Aplicaciones Gura",
    SECONDS: "Segundos",
    MOTION: "Movimiento",
    CONTRAST: "Contraste",
    WALLPAPER: "Fondo de pantalla",
    ADD: "Añadir",
    STYLE: "Estilo",
    WEIGHT: "Peso",
    ALIGNMENT: "Alineación",
    ALIGN_CENTER: "Centrado",
    ALIGN_LEFT: "Izquierda",
    ALIGN_RIGHT: "Derecha",
    ADJUST: "Ajustar",
    LANGPICK: "Idioma",
    RESET: "Borrar datos",
    RESET_BTN: "Restablecer",
    INSTALL_PROMPT: "Instale como una aplicación para obtener todas las funciones",
    OFFLINE: "Estás desconectado",
    ONLINE: "Estás conectado",
    FAIL_WEATHER: "No se pudo recuperar el clima",
    FULLSCREEN: "Pantalla completa",
    SETUP_COMPLETE: "Configuración completa",
    OPEN_SETTINGS: "Abrir ajustes",
    OPEN_WEATHER: "Abrir clima",
    APP_OPENED: "Aplicación {app} abierta",
    APP_OPEN_FAIL: "No se pudo abrir {app}",
    WALLPAPER_UPDATED: "Fondo de pantalla actualizado",
    WALLPAPER_UPDATE_FAIL: "No se pudo actualizar el fondo de pantalla",
    MULTIPLE_WALLPAPERS_UPDATED: "Múltiples fondos de pantalla actualizados",
    NO_VALID_WALLPAPERS: "No se encontraron fondos de pantalla válidos",
    WALLPAPER_CHANGE: "Fondo de pantalla cambiado",
    SLIDESHOW_WALLPAPER: "Fondo de pantalla de presentación de diapositivas",
    WALLPAPER_SAVE_FAIL: "No se pudo guardar el fondo de pantalla",
    WALLPAPER_HISTORY_FAIL: "No se pudo guardar el historial del fondo de pantalla",
    ALL_WALLPAPER_REMOVE: "Todos los fondos de pantalla eliminados",
    WALLPAPER_REMOVE: "Fondo de pantalla eliminado",
    LOAD_SUCCESS: "Monos cargado con éxito",
    NOT_FULLSCREEN: "No está en pantalla completa",
    CLOCK_STYLE_FAILED: "No se pudo cargar el estilo del reloj",
    CHECK_WORDS: ['actualizado', 'completo', 'listo', 'éxito', 'exitosamente', 'aceptado', 'aceptar', 'sí'],
    CLOSE_WORDS: ['fallido', 'cancelado', 'error', 'fracaso', 'cancelar', 'rechazado', 'rechazar', 'no'],
    DEFAULT: "Predeterminado",
    WORK: "Trabajo",
    PUFFY: "Esponjoso",
    CLASSIC: "Clásico",
    STROKES: "Trazos",
    MONO: "Mono",
    PIXEL: "Píxel",
    WRITTEN: "Escrito",
    RAISED: "Elevado",
    DOT: "Punto",
    ROUND: "Redondo",
    DETAIL_VERS: "Detalles",
    GET_DOCS: "Abrir docs",
    SETUP_SELECT_LANGUAGE: "Seleccionar idioma",
    SETUP_SELECT_LANGUAGE_DESC: "Puedes cambiar los idiomas más tarde en Controles ", 
    SETUP_HI_THERE: "Hola",
    SETUP_OPEN_PRIVATE: "Abierto y Privado",
    SETUP_OPEN_PRIVATE_DESC: "Tus datos permanecen en el dispositivo en todo momento. No se transfieren datos de usuario a nuestros servicios.",
    SETUP_ALLOW_PERMISSIONS: "Permitir permisos",
    SETUP_BASIC_ACCESS: "Acceso básico",
    SETUP_BASIC_ACCESS_DESC: "Permite que Monos funcione correctamente",
    SETUP_LOCATION_ACCESS: "Acceso a la ubicación",
    SETUP_LOCATION_ACCESS_DESC: "Permite el clima y los resultados personalizados",
    SETUP_NOTIFICATIONS: "Notificaciones",
    SETUP_NOTIFICATIONS_DESC: "Permite actualizaciones y alertas de temporizador",
    SETUP_CANNIBALIZE: "Personaliza tu Monos",
    SETUP_CLOCK_FORMAT: "Formato del reloj",
    SETUP_SHOW_SECONDS: "Mostrar segundos",
    SETUP_HIDE_SECONDS: "Ocultar segundos",
    SETUP_SHOW_WEATHER: "Mostrar u ocultar el clima",
    SETUP_SHOW_WEATHER_TRUE: "Mostrar el clima",
    SETUP_SHOW_WEATHER_FALSE: "Ocultar el clima",
    SETUP_GURAPPS_USAGE: "Uso de Aplicaciones Gura",
    SETUP_GURAPPS_USAGE_DESC: "Para usar Aplicaciones Gura, desliza hacia arriba desde la barra inferior y elige una Gurapp para iniciar.",
    SETUP_CONFIGURE_OPTIONS: "Configurar más opciones en los controles",
    SETUP_CONFIGURE_OPTIONS_DESC: "Presiona Controles en la esquina superior derecha o accede a los Controles en la aplicación presionando el reloj.",
    SETUP_GET_STARTED: "Empezar",
    SETUP_CONTINUE: "Continuar",
    SETUP_LIGHT: "Claro",
    SETUP_DARK: "Oscuro",
    RESET_OPTIONS: "Seleccione Aceptar para un restablecimiento completo o Cancelar para restablecer solo la configuración del reloj",
    CLOCK_RESET_SUCCESS: "Los datos del reloj se han borrado correctamente.",
    RESET_CONFIRM: "¿Está seguro de que desea borrar todos los datos? Esta acción no se puede deshacer.",
    RESET_SUCCESS: "Todos los datos se han borrado correctamente.",
    LARGE_SCR_REQ: "Se requiere una pantalla más grande",
    DONT_CLOSE: "Utilice el modo de suspensión en los controles para apagar",
    CLOCK_COLOR: "Color del reloj",
    N_WALL: "Sin fondos de pantalla",
    CLOCK_STACK: "Pila de reloj",
    GURAPP_OFF: "Los Gurapps están actualmente deshabilitados",
    GURAPP_NOT_INSTALLED: "Esta aplicación no está instalada",
    GURAPP_OFFLINE_NOT_SUPPORTED: "La instalación sin conexión no es compatible con este navegador",
    GURAPP_INSTALL_FAILED: "La instalación sin conexión falló para {appName}",
    GURAPP_DELETED: "{appName} fue eliminada",
    GURAPP_DELETE_FAILED: "Error: No se pudo encontrar {appName} para eliminar",
    GURAPP_DELETE_ASK: "¿Está seguro de que desea eliminar {appName}?",
    GURAPP_DELETE_STORE_DENIED: "La App Store no se puede eliminar",
    GURAPP_INSTALLING: "Instalando {appName}",
    GURAPP_INSTALL_EXISTS: "{appName} ya está instalada",
    GURAPP_INSTALL_NONSTORE_DENIED: "Error: Solo la App Store de Monos puede instalar aplicaciones"
};

const LANG_KO = {
    GREETING: "Monos가 성공적으로 로드되었습니다",
    LICENCE: "Monos는 kirbIndustries에서 제작되었으며 CC BY-NC 4.0에 따라 라이선스가 부여됩니다.",
    WELCOME_MESSAGE: "안녕하세요, Monos에 오신 것을 환영합니다!",
    PLACEHOLDER_MESSAGE: "메시지를 입력하세요",
    SEND: "보내기",
    VOICE: "음성",
    CONTROLS: "컨트롤",
    SILENT: "무음",
    TONE: "톤",
    MINIMAL: "집중",
    DARKMODE: "주광",
    WEATHER: "날씨",
    GURAPPS: "구라앱",
    SECONDS: "초",
    MOTION: "모션",
    CONTRAST: "대비",
    WALLPAPER: "배경 화면",
    ADD: "추가",
    STYLE: "스타일",
    WEIGHT: "두께",
    ALIGNMENT: "정렬",
    ALIGN_CENTER: "가운데",
    ALIGN_LEFT: "왼쪽",
    ALIGN_RIGHT: "오른쪽",
    ADJUST: "조정",
    LANGPICK: "언어",
    RESET: "데이터 삭제",
    RESET_BTN: "초기화",
    INSTALL_PROMPT: "모든 기능을 사용하려면 앱으로 설치하세요",
    OFFLINE: "오프라인 상태입니다",
    ONLINE: "온라인 상태입니다",
    FAIL_WEATHER: "날씨를 가져오지 못했습니다",
    FULLSCREEN: "전체 화면",
    SETUP_COMPLETE: "설정 완료",
    OPEN_SETTINGS: "설정 열기",
    OPEN_WEATHER: "날씨 열기",
    APP_OPENED: "{app} 앱이 열렸습니다",
    APP_OPEN_FAIL: "{app} 앱을 열 수 없습니다",
    WALLPAPER_UPDATED: "배경 화면이 업데이트되었습니다",
    WALLPAPER_UPDATE_FAIL: "배경 화면 업데이트에 실패했습니다",
    MULTIPLE_WALLPAPERS_UPDATED: "여러 배경 화면이 업데이트되었습니다",
    NO_VALID_WALLPAPERS: "유효한 배경 화면을 찾을 수 없습니다",
    WALLPAPER_CHANGE: "배경 화면이 변경되었습니다",
    SLIDESHOW_WALLPAPER: "슬라이드 쇼 배경 화면",
    WALLPAPER_SAVE_FAIL: "배경 화면 저장에 실패했습니다",
    WALLPAPER_HISTORY_FAIL: "배경 화면 기록 저장에 실패했습니다",
    ALL_WALLPAPER_REMOVE: "모든 배경 화면이 제거되었습니다",
    WALLPAPER_REMOVE: "배경 화면이 제거되었습니다",
    LOAD_SUCCESS: "Monos가 성공적으로 로드되었습니다",
    NOT_FULLSCREEN: "전체 화면이 아닙니다",
    CLOCK_STYLE_FAILED: "시계 스타일 로드에 실패했습니다",
    CHECK_WORDS: ['업데이트됨', '완료됨', '완료', '성공', '성공적으로', '수락됨', '수락', '예'],
    CLOSE_WORDS: ['실패', '취소됨', '오류', '실패', '취소', '거부됨', '거부', '아니요'],
    DEFAULT: "기본",
    WORK: "작업",
    PUFFY: "푹신한",
    CLASSIC: "클래シック",
    STROKES: "획",
    MONO: "모노",
    PIXEL: "픽셀",
    WRITTEN: "필기체",
    RAISED: "돌출된",
    DOT: "점",
    ROUND: "둥근",
    DETAIL_VERS: "세부 정보",
    GET_DOCS: "문서 열기",
    SETUP_SELECT_LANGUAGE: "언어 선택",
    SETUP_SELECT_LANGUAGE_DESC: "나중에 컨트롤에서 언어를 변경할 수 있습니다. ", 
    SETUP_HI_THERE: "안녕하세요",
    SETUP_OPEN_PRIVATE: "개방형 및 개인 정보 보호",
    SETUP_OPEN_PRIVATE_DESC: "사용자 데이터는 항상 장치에 보관됩니다. 사용자 데이터는 서비스로 전송되지 않습니다.",
    SETUP_ALLOW_PERMISSIONS: "권한 허용",
    SETUP_BASIC_ACCESS: "기본 액세스",
    SETUP_BASIC_ACCESS_DESC: "Monos가 제대로 작동하도록 합니다.",
    SETUP_LOCATION_ACCESS: "위치 정보 액세스",
    SETUP_LOCATION_ACCESS_DESC: "날씨 및 맞춤형 결과를 활성화합니다.",
    SETUP_NOTIFICATIONS: "알림",
    SETUP_NOTIFICATIONS_DESC: "업데이트 및 타이머 알림을 활성화합니다.",
    SETUP_CANNIBALIZE: "Monos를 사용자 정의",
    SETUP_CLOCK_FORMAT: "시계 형식",
    SETUP_SHOW_SECONDS: "초 표시",
    SETUP_HIDE_SECONDS: "초 숨기기",
    SETUP_SHOW_WEATHER: "날씨 표시 또는 숨기기",
    SETUP_SHOW_WEATHER_TRUE: "날씨 표시",
    SETUP_SHOW_WEATHER_FALSE: "날씨 숨기기",
    SETUP_GURAPPS_USAGE: "구라앱 사용법",
    SETUP_GURAPPS_USAGE_DESC: "구라앱 사용하려면 하단 막대에서 위로 스와이프하고 시작할 Gurapp을 선택하십시오.",
    SETUP_CONFIGURE_OPTIONS: "컨트롤에서 추가 옵션 구성",
    SETUP_CONFIGURE_OPTIONS_DESC: "오른쪽 상단의 컨트롤을 누르거나 시계를 눌러 앱에서 컨트롤에 액세스합니다.",
    SETUP_GET_STARTED: "시작하기",
    SETUP_CONTINUE: "계속",
    SETUP_LIGHT: "밝게",
    SETUP_DARK: "어둡게",
    RESET_OPTIONS: "전체 재설정을 원하시면 확인을 선택하시고, 시계 설정만 재설정하시려면 취소를 선택하세요.",
    CLOCK_RESET_SUCCESS: "시계 데이터가 성공적으로 삭제되었습니다.",
    RESET_CONFIRM: "모든 데이터를 지우시겠습니까? 이 작업은 되돌릴 수 없습니다.",
    RESET_SUCCESS: "모든 데이터가 성공적으로 지워졌습니다.",
    LARGE_SCR_REQ: "더 큰 화면이 필요합니다",
    DONT_CLOSE: "끄려면 컨트롤에서 잠자기를 사용하세요",
    CLOCK_COLOR: "시계 색상",
    N_WALL: "배경 화면 없음",
    CLOCK_STACK: "시계 스택",
    GURAPP_OFF: "Gurapps는 현재 비활성화되어 있습니다",
    GURAPP_NOT_INSTALLED: "이 앱이 설치되지 않았습니다",
    GURAPP_OFFLINE_NOT_SUPPORTED: "이 브라우저에서는 오프라인 설치가 지원되지 않습니다",
    GURAPP_INSTALL_FAILED: "{appName} 오프라인 설치 실패",
    GURAPP_DELETED: "{appName} 이(가) 삭제되었습니다",
    GURAPP_DELETE_FAILED: "오류: 삭제할 {appName}을(를) 찾을 수 없습니다",
    GURAPP_DELETE_ASK: "{appName}을(를) 삭제하시겠습니까?",
    GURAPP_DELETE_STORE_DENIED: "앱 스토어는 삭제할 수 없습니다",
    GURAPP_INSTALLING: "{appName} 설치 중",
    GURAPP_INSTALL_EXISTS: "{appName}은(는) 이미 설치되어 있습니다",
    GURAPP_INSTALL_NONSTORE_DENIED: "오류: Monos 앱 스토어만 앱을 설치할 수 있습니다"
};

const LANG_ZH = {
    GREETING: "Monos加载成功",
    LICENCE: "Monos由kirbIndustries制作，CC BY-NC 4.0",
    WELCOME_MESSAGE: "你好，欢迎来到Monos！",
    PLACEHOLDER_MESSAGE: "输入您的消息",
    SEND: "发送",
    VOICE: "语音",
    CONTROLS: "控制",
    SILENT: "静音",
    TONE: "音调",
    MINIMAL: "专注",
    DARKMODE: "日光",
    WEATHER: "天气",
    GURAPPS: "古拉应用程序",
    SECONDS: "秒",
    MOTION: "运动",
    CONTRAST: "对比度",
    WALLPAPER: "壁纸",
    ADD: "添加",
    STYLE: "样式",
    WEIGHT: "粗细",
    ALIGNMENT: "对齐",
    ALIGN_CENTER: "居中",
    ALIGN_LEFT: "左对齐",
    ALIGN_RIGHT: "右对齐",
    ADJUST: "调整",
    LANGPICK: "语言",
    RESET: "清除数据",
    RESET_BTN: "重置",
    INSTALL_PROMPT: "安装为应用程序以获取所有功能",
    OFFLINE: "您已离线",
    ONLINE: "您已在线",
    FAIL_WEATHER: "无法检索天气",
    FULLSCREEN: "全屏",
    SETUP_COMPLETE: "设置完成",
    OPEN_SETTINGS: "打开设置",
    OPEN_WEATHER: "打开天气",
    APP_OPENED: "{app}应用程序已打开",
    APP_OPEN_FAIL: "无法打开{app}",
    WALLPAPER_UPDATED: "壁纸已更新",
    WALLPAPER_UPDATE_FAIL: "无法更新壁纸",
    MULTIPLE_WALLPAPERS_UPDATED: "多个壁纸已更新",
    NO_VALID_WALLPAPERS: "找不到有效的壁纸",
    WALLPAPER_CHANGE: "壁纸已更改",
    SLIDESHOW_WALLPAPER: "幻灯片壁纸",
    WALLPAPER_SAVE_FAIL: "无法保存壁纸",
    WALLPAPER_HISTORY_FAIL: "无法保存壁纸历史记录",
    ALL_WALLPAPER_REMOVE: "所有壁纸已删除",
    WALLPAPER_REMOVE: "壁纸已删除",
    LOAD_SUCCESS: "Monos加载成功",
    NOT_FULLSCREEN: "不是全屏",
    CLOCK_STYLE_FAILED: "无法加载时钟样式",
    CHECK_WORDS: ['已更新', '完成', '完成', '成功', '成功地', '已接受', '接受', '是'],
    CLOSE_WORDS: ['失败', '已取消', '错误', '失败', '取消', '已拒绝', '拒绝', '不'],
    DEFAULT: "默认",
    WORK: "工作",
    PUFFY: "蓬松",
    CLASSIC: "经典",
    STROKES: "笔画",
    MONO: "单色",
    PIXEL: "像素",
    WRITTEN: "手写",
    RAISED: "凸起",
    DOT: "点",
    ROUND: "圆形",
    DETAIL_VERS: "详细信息",
    GET_DOCS: "打开文档",
    SETUP_SELECT_LANGUAGE: "选择语言",
    SETUP_SELECT_LANGUAGE_DESC: "您可以在之后的“控制”中更改语言 ",
    SETUP_HI_THERE: "你好",
    SETUP_OPEN_PRIVATE: "开放和隐私",
    SETUP_OPEN_PRIVATE_DESC: "您的数据始终保留在设备上。用户数据不会传输到我们的任何服务。",
    SETUP_ALLOW_PERMISSIONS: "允许权限",
    SETUP_BASIC_ACCESS: "基本访问",
    SETUP_BASIC_ACCESS_DESC: "使Monos正常工作",
    SETUP_LOCATION_ACCESS: "位置访问",
    SETUP_LOCATION_ACCESS_DESC: "启用天气和个性化结果",
    SETUP_NOTIFICATIONS: "通知",
    SETUP_NOTIFICATIONS_DESC: "启用更新和计时器提醒",
    SETUP_CANNIBALIZE: "自定义您的Monos",
    SETUP_CLOCK_FORMAT: "时钟格式",
    SETUP_SHOW_SECONDS: "显示秒数",
    SETUP_HIDE_SECONDS: "隐藏秒数",
    SETUP_SHOW_WEATHER: "显示或隐藏天气",
    SETUP_SHOW_WEATHER_TRUE: "显示天气",
    SETUP_SHOW_WEATHER_FALSE: "隐藏天气",
    SETUP_GURAPPS_USAGE: "古拉应用程序的使用",
    SETUP_GURAPPS_USAGE_DESC: "要使用古拉应用程序，请从底部药丸向上滑动并选择要启动的古拉应用程序。",
    SETUP_CONFIGURE_OPTIONS: "在控件中配置更多选项",
    SETUP_CONFIGURE_OPTIONS_DESC: "按右上角的控件或通过按时钟访问应用程序中的控件。",
    SETUP_GET_STARTED: "开始",
    SETUP_CONTINUE: "继续",
    SETUP_LIGHT: "浅色",
    SETUP_DARK: "深色",
    RESET_OPTIONS: "选择“确定”进行完全重置，或选择“取消”仅重置时钟设置",
    CLOCK_RESET_SUCCESS: "时钟数据已成功清除。",
    RESET_CONFIRM: "确定要清除所有数据吗？此操作无法撤消。",
    RESET_SUCCESS: "所有数据已成功清除。",
    LARGE_SCR_REQ: "需要更大的屏幕",
    DONT_CLOSE: "使用控件中的睡眠模式关闭",
    CLOCK_COLOR: "时钟颜色",
    N_WALL: "没有壁纸",
    CLOCK_STACK: "时钟堆栈",
    GURAPP_OFF: "Gurapps 当前已禁用",
    GURAPP_NOT_INSTALLED: "此应用程序未安装",
    GURAPP_OFFLINE_NOT_SUPPORTED: "此浏览器不支持离线安装",
    GURAPP_INSTALL_FAILED: "{appName} 的离线安装失败",
    GURAPP_DELETED: "{appName} 已删除",
    GURAPP_DELETE_FAILED: "错误：找不到要删除的 {appName}",
    GURAPP_DELETE_ASK: "您确定要删除 {appName} 吗？",
    GURAPP_DELETE_STORE_DENIED: "App Store 无法删除",
    GURAPP_INSTALLING: "正在安装 {appName}",
    GURAPP_INSTALL_EXISTS: "{appName} 已安装",
    GURAPP_INSTALL_NONSTORE_DENIED: "错误：只有 Monos 应用商店才能安装应用"
}
